### ISSUE TITLE
Can't add an entity to HA

### ISSUE THREAD

**Issue by chri93m8** [dingusdk/haihcviewer#27]
Hallo 
I am new to HA and i am trying to add a light by using IHCViewer but im geting an error can someone help?

(https://user-images.githubusercontent.com/44833159/215861133-9dd15599-77ee-4c65-af56-53fda60ba806.png)

Log:
2023-01-31 20:35:00.459 WARNING (SyncWorker_6) [custom_components.ihcviewer.api.mapper] The id 56154, was not found as an entity state
2023-01-31 20:35:00.463 WARNING (SyncWorker_6) [custom_components.ihcviewer.api.mapper] The id 56667, was not found as an entity state
2023-01-31 20:35:00.464 WARNING (SyncWorker_6) [custom_components.ihcviewer.api.mapper] The id 56667, was not found as an entity state
2023-01-31 20:35:00.464 WARNING (SyncWorker_6) [custom_components.ihcviewer.api.mapper] The id 56667, was not found as an entity state
2023-01-31 20:35:00.465 WARNING (SyncWorker_6) [custom_components.ihcviewer.api.mapper] The id 56667, was not found as an entity state
2023-01-31 20:35:00.465 WARNING (SyncWorker_6) [custom_components.ihcviewer.api.mapper] The id 56667, was not found as an entity state

thank in advance

**Comment by dingusdk** [comment]
I think there is something wrong in your ihc_manual_setup.yaml file. 

Can you show the content your ihc_manual_setup.yaml file? 
Have you changed the file manually or only using IHCViewer?

**Comment by chri93m8** [comment]
Hey Jens

sorry for the late response i have been away on a business trip the last few days.

here is a screendump from the ihc_manual_setup.yaml file
![image](https://user-images.githubusercontent.com/44833159/216786698-35621397-0097-4c49-a745-f7a4f864eff9.png)

I have not been editing the file manually.

**Comment by chri93m8** [comment]
I tried removing some of the repeating resource ID's manually but now i am geting a new error.
i don't know if it is important but the project is not loading in to the viewer but the log and info tab still work

New error Log:

Denne fejl stammer fra en brugerdefineret integration.

Logger: aiohttp.server
Source: custom_components/ihcviewer/api/project.py:22
Integration: IHC Viewer (documentation)
First occurred: 22.10.05 (2 occurrences)
Last logged: 22.10.18

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_response.py", line 664, in body
    self._body = body = payload.PAYLOAD_REGISTRY.get(body)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/payload.py", line 118, in get
    raise LookupError()
aiohttp.payload.LookupError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 145, in handle
    result = await result
  File "/config/custom_components/ihcviewer/api/project.py", line 22, in get
    return web.Response(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_response.py", line 639, in __init__
    self.body = body
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_response.py", line 666, in body
    raise ValueError("Unsupported body type %r" % type(body))
ValueError: Unsupported body type <class 'bool'>

**Comment by dingusdk** [comment]
There is not any news on this issue so I will close it.

I have not had any errors similar to what you are reporting. If you are still having problems, create a new issue here.

It may also be an idea to clear you browser data - in chrome you can ctrl+shift+i - then go to the application tab and click the "clear site data" button. Then refresh the page  (You will have login to HA again)
