### ISSUE TITLE
Error loading IHCViewer

### ISSUE THREAD

**Issue by Infernoken76** [dingusdk/haihcviewer#30]
HomeAssistant on Intel NUC running HAOS

IHC Controller HW6.1
Firmware 2.7.220

I cannot get the IHCViewer loaded, seems also linked to errors I'm getting with IHC Beta Integration...

Reboot of HA and/or the IHC controller does not resolve the issue:

```
This error originated from a custom integration.

Logger: aiohttp.server
Source: custom_components/ihcviewer/api/project.py:19
Integration: IHC Viewer (documentation)
First occurred: 7:58:50 PM (2 occurrences)
Last logged: 8:06:45 PM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 148, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ihcviewer/api/project.py", line 19, in get
    project = await self.hass.async_add_executor_job(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ihcsdk/ihccontroller.py", line 142, in get_project
    self._project = self.client.get_project_in_segments()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ihcsdk/ihcclient.py", line 122, in get_project_in_segments
    buffer.write(self.get_project_segment(s, projectMajor, projectMinor))
TypeError: a bytes-like object is required, not 'bool'

```

**Comment by dingusdk** [comment]
The issue above is the viewer is not able to load IHC project from the controller.
I think you would have a similar error from the IHC integration itself, because the IHC integration also need the IHC project.
The only know issue/fix i know of is to reboot the IHC controller, then restart HA
I will close this issue for now. If you still have the problem create a new issue, and check if you have a similar error from the IHC integration itself.
